---
date: '2021 3 16 '
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
library("gridExtra")
library(nycflights13)
```
### 통계학세미나 HW #2 
### 212STG04 김이현 


### 1번 
#### "blue"는 데이터 mpg에 있는 값이 아니다. 
#### 따라서 color = "blue" 라는 코드를  mapping 하지않고 밖에 써야한다. 
```{r fig.height=4,fig.width=4}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy),color = "blue")
```

### 2번 
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() + geom_smooth()->p2_1

ggplot() +
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))->p2_2
grid.arrange(p2_1,p2_2,nrow=1)
```

##
다른 그래프가 아니다. 
데이터도 동일하고, x,y로 mapping하고자 하는 변수가 x = displ, y = hwy로 동일하기 때문에, 이를 각각의 그래프 함수 안에서 mapping을 하든, ggplot()에서 한번에 mapping하든 동일한 그래프가 나온다. 



### 3번 
```{r}
ggplot(data = mpg,aes(x = displ, y = hwy)) +
  geom_point()+geom_smooth(se=F) ->p3_1
ggplot(data = mpg,aes(x = displ, y = hwy, group=drv)) +
  geom_point()+geom_smooth(se=F) -> p3_2
grid.arrange(p3_1,p3_2,nrow=1)

ggplot(mpg,aes(displ,hwy,color=drv))+
  geom_point(size=2)+geom_smooth(se=F) -> p3_3
ggplot(mpg)+
  geom_point(aes(displ,hwy,color=drv),size=2)+
  geom_smooth(aes(displ,hwy),se=F)-> p3_4

ggplot(mpg,aes(displ,hwy))+
  geom_point(aes(color=drv),size=2)+
  geom_smooth(aes(linetype=drv),se=F)->p3_5

ggplot(mpg,aes(displ,hwy))+
  geom_point(color="white",size=5)+
  geom_point(aes(color=drv),size=2)->p3_6

grid.arrange(p3_3,p3_4,p3_5,p3_6,nrow=2)
```

### 4번 
```{r}
data("flights")
#4-1 
flights %>% filter(arr_delay>=120)  
#4-2 
flights %>% filter(dest=="HOU")
#4-3 
flights %>% filter(carrier %in% c("AA","UA","DL"))

#4-4 
flights %>% filter(month%in%c(7,8,9)) 

#4-5
flights %>% filter(arr_delay>=120 & dep_delay<=0) 

#4-6 
flights %>% mutate(makeup = dep_delay -arr_delay) %>%
  filter(dep_delay>=60 & makeup >=30)
#4-7
flights %>% filter(dep_time>=0 & dep_time<=600) 
```

